### ISSUE TITLE
SAML/SSO setup for Studio

### ISSUE THREAD

**Issue by jurv11** [iterative/studio-support#31] opened 2021-09-14 21:10 UTC
How is access set up for organizations with GitHub? Adding this as we had a question from a prospect: "If we have SAML/SSO setup with our GitHub Enterprise Organization, do we also need SAML/SSO setup for DVC Studio, or is access based on repo access within GitHub?"

**Comment by mvshmakov** [comment] 2021-09-15 09:23
Hey, @jurv11, thanks for the question!

Currently, we don't have support for the external SAML/SSO identity providers (other then main git providers we work with - GitHub/GitLab/Bitbucket) directly in the Studio, so the flow of user sign-in will look this way:
1) The user authenticates on the GitHub Enterprise through SAML/SSO identity provider.
2) The user authenticates in the DVC Studio using the GitHub-provided SAML/SSO. In this case for the Studio, it does not matter which authentication method is used on GitHub as long as the user is logged in.
3) The user [installs a GitHub app](https://docs.github.com/en/developers/apps/managing-github-apps/installing-github-apps) to provide the Studio with a way to interact with the repositories.

And, @duijf, correct me if I'm wrong, but we can't yet provide the service which is tight up with GitHub Enterprise on our SaaS platform directly, so there is a need to get the on-premise edition of the Studio and set it up with the correct GitHub Enterprise URLs.

**Comment by duijf** [comment] 2021-09-22 14:25
Note that GitHub has two Enterprise related products:

 - GitHub Enterprise Server. Self hosted, "on premise" in AWS/GCP/Azure/some datacenter/...
 - GitHub Enterprise Cloud. Managed by GitHub, hosted on GitHub.com, but still has enterprise features such as SAML support.

Using GitHub Enterprise Server with Studio currently requires an on-prem deployment of Studio.

> 2. The user authenticates in the DVC Studio using the GitHub-provided SAML/SSO. In this case for the Studio, it does not matter which authentication method is used on GitHub as long as the user is logged in.

If GitHub auth for SAML users indeed works this way, then we already support GitHub Enterprise Cloud SAML accounts. We should confirm this specifically though; I don't think we have tested this before.

## Summary

 - GitHub.com: Plain "Sign in with GitHub". Works.
 - GitHub Enterprise Cloud (regular user): Same as GitHub.com.
 - GitHub Enterprise Cloud (SAML user): Need to confirm whether this works as above. Update: this works as expected.
 - GitHub Enterprise Server (on prem): Using this together with our Studio SaaS instance on `studio.iterative.ai` is currently not possible and adding support will not be trivial.

Hope that helps clarify things a bit further @jurv11.

I will continue to investigate the status of GHE Cloud + SAML users.

**Comment by duijf** [comment] 2021-11-12 08:14
Confirmed that GHE Cloud + SAML users works together nicely with our GitHub app. Closing this one, since there is nothing left to do here.

**Closed as completed by duijf** 2021-11-12 08:14 UTC
Labels: question, priority-p1
