### ISSUE TITLE
DVC studio not able to pic project which is not in root dir of DVC Studio

### ISSUE THREAD

**Issue by RajeshThakur123222** [iterative/studio-support#54] opened 2022-07-20 13:57 UTC
Hi DVC Team,

we were exploring the DVC and we found one bug

step to replicate

step1:- 
I have my project in github which has the root dir is the root
inside of root dir, we have many projects, one project is related to DVC

but when we are trying to configure DVC studio with our child dir

![image](https://user-images.githubusercontent.com/98795191/180000168-e1665436-c8d6-4895-b448-40380d7e9e3f.png)

but somehow after configuring the project, DVC is picking the URL like <remote_repo><child_dir>
actually, it should pick <remote_repo>/<child_dir>

**Comment by jorgeorpinel** [comment] 2022-07-20 20:24
Looks like a dupe of #55 (or vice versa, but there's already some follow-up there).

**Closed as not planned by jorgeorpinel** 2022-07-20 20:24 UTC
Labels: duplicate
