### ISSUE TITLE
Bug: Changes not reflected in Studio View

### ISSUE THREAD

**Issue by karpatika92** [iterative/studio-support#43] opened 2021-12-10 14:49 UTC
If I change mandatory columns in my project, the change has no effect, and I get the same UI ass before the changes. On the other hand, if I delete the view and create a new one with different mandatory fields, it works.

**Comment by shcheklein** [comment] 2021-12-11 00:48
@karpatika92 do you have a lot of columns? Most likely, this "mandatory columns" configuration takes effect (confusingly) only if number of columns exceeds our parser threshold - I think it's 200 now. If it doesn't exceed you would usually don't need this since you could use the regular column picker:

<img width="401" alt="Screen Shot 2021-12-10 at 4 47 41 PM" src="https://user-images.githubusercontent.com/3659196/145657547-8175faf9-0a47-4034-bf01-ee02453d1650.png">

Could you please clarify your use case?

@Suor @tapadipti - looks like this logic is still confusing, wdyt? I was able to reproduce this on this view:

https://studio.iterative.ai/user/shcheklein/views/example-get-started-1n4u8ylmz0

`avr_prec` is available:

<img width="669" alt="Screen Shot 2021-12-10 at 4 43 46 PM" src="https://user-images.githubusercontent.com/3659196/145657405-59aa2782-c0e1-4f34-bef7-030875f28560.png">

even though it's disable in the mandatory columns:

<img width="602" alt="Screen Shot 2021-12-10 at 4 45 09 PM" src="https://user-images.githubusercontent.com/3659196/145657449-22b20fa9-8966-4359-84a0-6dd7fd8e8be8.png">

**Comment by tapadipti** [comment] 2021-12-15 06:56
Yes, mandatory columns takes effect only when there are more than 200 columns. This is how it works:

>If you simply want to hide certain columns, you can hide them by using the `Columns` filter within the view table. If your repository exceeds 200 columns, and you want to guarantee the inclusion of some columns, then use the `Mandatory columns` setting. When the repository has over 200 columns, Studio will import a subset. The columns that are not imported will not be available to display in your view. Using `Mandatory columns` setting, you can select which columns are mandatory to import. Studio will also import unselected columns up to a maximum of 200.

@karpatika92 could you pls elaborate your scenario: When you say `the change has no effect`, does it mean that the columns that you marked as mandatory are not visible or that the columns that you did not mark as mandatory are visible. If it's the former, it could be a bug. If it's the latter, can you confirm if you have more than 200 columns; and how many columns you have marked as mandatory?

@shcheklein  The role of mandatory columns is indeed still confusing. This is being tracked in the internal ticket https://github.com/iterative/viewer/issues/2253 and I've added some suggestions to change the messaging. In your example above, you have only 16 columns, so they will all be displayed unless you hide them.

**Comment by Suor** [comment] 2021-12-15 07:24
I suggest we rewrite the logic, i.e. only selected columns are gathered any other are skipped. Whatever we have now we've failed to explained several times. The only downside people will need to reimport stuff if they need to add any new column, which is almost always the case now anyway, since the limit is usually filled.

**Comment by tapadipti** [comment] 2021-12-15 11:59
Thanks @Suor 
If we change this logic, it'll be good to select up to 200 columns (mark them as mandatory) by default for all new views.
And may be also automatically mark up to 200 columns (including the ones that the user marked as mandatory) as mandatory for all existing views.

**Comment by tapadipti** [comment] 2022-01-03 08:12
@karpatika92 We are trying to determine the changes/fixes required to resolve this issue. Could you pls elaborate your scenario: When you said `the change has no effect`, did it mean that the columns that you marked as mandatory were not visible or that the columns that you did not mark as mandatory were visible. If it's the former, it could be a bug. If it's the latter, do you know if you had more than 200 columns; and how many columns you had marked as mandatory?

**Comment by tapadipti** [comment] 2023-04-05 09:37
@karpatika92 We've changed the `Mandatory columns` setting to `Columns`. Now, only those columns that you have selected in the `Columns` setting are imported by Studio. Unselected columns will not be available in your project. This should make the setting easier to understand and use, and I believe this resolves your issue. 

So I'm closing this issue. Pls let us know or re-open the issue if your problem is still not resolved.

**Closed as completed by tapadipti** 2023-04-05 09:37 UTC
Labels: triage
